{{- if .Values.verification.postInstallCheck }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "chart.name" . }}-post-upgrade-check"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: post-upgrade-hook
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  restartPolicy: Never
  containers:
  - name: post-upgrade-check
    image: bitnami/kubectl:latest
    command:
      - /bin/sh
      - -c
      - |
        {{- include "chart.verificationScript" (dict "hookType" "Post-upgrade" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 8 }}
  serviceAccountName: {{ .Values.controller.serviceAccountName }}
{{- end }}
