---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tagemon-controller-role
rules:
# Tagemon resource permissions
- apiGroups:
  - tagemon.io
  resources:
  - tagemons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# Tagemon status permissions
- apiGroups:
  - tagemon.io
  resources:
  - tagemons/status
  verbs:
  - get
  - patch
  - update
# Tagemon finalizer permissions
- apiGroups:
  - tagemon.io
  resources:
  - tagemons/finalizers
  verbs:
  - update 