# This rule is not used by the project tagemon-dev itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to tagemon-controller.tagemon.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tagemon-dev
    app.kubernetes.io/managed-by: kustomize
  name: tagemon-viewer-role
rules:
- apiGroups:
  - tagemon-controller.tagemon.io
  resources:
  - tagemons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tagemon-controller.tagemon.io
  resources:
  - tagemons/status
  verbs:
  - get
